# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Using Docker via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY}}
        port: 22
        script: |
          cd ~/wabot-test
          git pull origin master
          git status
          docker container stop wabot-app
          docker rm wabot-app
          docker build -t wabot-image .
          
          docker run docker run -d -it  -p 80:80/tcp --name wabot-app wabot-image:latest
